import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import api from '../api/client';
import type { Activity, DashboardMetrics, PipelineStageSummary, RepPerformance } from '../types';

const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', notation: value >= 1000000 ? 'compact' : 'standard', maximumFractionDigits: 1 }).format(value);
const stageName = (stage: string) => stage.replace('_', ' ').toLowerCase().replace(/\b\w/g, c => c.toUpperCase());
export default function DashboardPage() {
  const { user, isManager } = useAuth(); const [metrics, setMetrics] = useState<DashboardMetrics | null>(null); const [pipeline, setPipeline] = useState<PipelineStageSummary[]>([]); const [activities, setActivities] = useState<Activity[]>([]); const [team, setTeam] = useState<RepPerformance[]>([]); const [error, setError] = useState('');
  useEffect(() => { (async () => { try { const requests = [api.get('/dashboard/metrics'), api.get('/dashboard/pipeline-summary'), api.get('/activities', { params: { upcoming: true } })]; if (isManager) requests.push(api.get('/dashboard/team-performance')); const results = await Promise.all(requests); setMetrics(results[0].data.metrics); setPipeline(results[1].data.pipelineSummary); setActivities(results[2].data.activities); if (isManager) setTeam(results[3].data.teamPerformance); } catch { setError('Dashboard data could not be loaded. Please refresh and try again.'); } })(); }, [isManager]);
  if (!metrics && !error) return <div className="fade-in py-20 text-stone">Preparing your workspace…</div>;
  if (error || !metrics) return <div className="fade-in border-l-2 border-signal-negative py-5 pl-5 text-signal-negative">{error || 'Dashboard data could not be loaded.'}</div>;
  const dashboard = metrics;
  const maxPipeline = Math.max(...pipeline.map(item => item.totalValue), 1); const topTeam = [...team].sort((a,b) => b.wonValue - a.wonValue).slice(0, 3);
  return <div className="fade-in">
    <section className="grid items-end gap-10 lg:grid-cols-[1.3fr_.7fr]"><div><p className="eyebrow">Sales intelligence / {isManager ? 'All territories' : 'Personal territory'}</p><h1 className="page-title">Good to see you,<br/><i>{user?.name?.split(' ')[0] ?? 'there'}.</i></h1><p className="page-intro">A live view of the relationships, opportunities, and follow-through that move your pipeline forward.</p></div><div className="border-l border-hairline pl-6 lg:pb-2"><p className="eyebrow">Open pipeline</p><p className="mt-2 font-[family-name:var(--font-display)] text-5xl tracking-[-.05em] tabular-nums text-charcoal">{money(dashboard.pipelineValue)}</p><p className="mt-3 text-sm text-stone">{dashboard.openOpportunities} active opportunity{dashboard.openOpportunities === 1 ? '' : 'ies'}</p></div></section>
    <section className="mt-14 grid border-y border-hairline md:grid-cols-4">{[{ label:'Prospects', value:dashboard.totalLeads },{ label:'Win rate', value:`${dashboard.conversionRate}%` },{ label:'Won value', value:money(dashboard.wonValue) },{ label:'Due today', value:dashboard.followUpsDueToday }].map((item,index) => <div key={item.label} className={`py-7 ${index ? 'border-t border-hairline md:border-l md:border-t-0 md:pl-7' : ''} ${index < 3 ? 'md:pr-7' : 'md:pl-7'}`}><p className="eyebrow">{item.label}</p><p className="mt-2 font-[family-name:var(--font-display)] text-4xl tracking-[-.05em] tabular-nums">{item.value}</p></div>)}</section>
    <section className="mt-16 grid gap-14 xl:grid-cols-[1.3fr_.7fr]"><div><div className="flex items-end justify-between"><div><p className="eyebrow">Pipeline cadence</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl tracking-[-.045em]">Where momentum lives.</h2></div><Link to="/pipeline" className="hidden text-[.68rem] font-semibold uppercase tracking-[.12em] text-bronze hover:text-[#8C5A3C] sm:block">Explore pipeline →</Link></div><div className="mt-8 space-y-5">{pipeline.filter(item => !['WON','LOST'].includes(item.stage)).map(item => <div key={item.stage} className="group grid grid-cols-[minmax(7rem,.65fr)_1.45fr_auto] items-center gap-3"><div><p className="text-sm font-semibold">{stageName(item.stage)}</p><p className="font-[family-name:var(--font-ticker)] text-[.65rem] text-stone">{item.count} DEAL{item.count === 1 ? '' : 'S'}</p></div><div className="h-[3px] overflow-hidden bg-[#EEDBCB]"><div className="h-full origin-left bg-bronze transition-transform duration-700 group-hover:scale-x-[1.02]" style={{width:`${Math.max(item.totalValue / maxPipeline * 100, 2)}%`}}/></div><p className="font-[family-name:var(--font-display)] text-xl tabular-nums">{money(item.totalValue)}</p></div>)}</div></div>
    <aside className="border-t border-hairline pt-7 xl:border-l xl:border-t-0 xl:pl-10 xl:pt-0"><p className="eyebrow">Next actions</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-3xl tracking-[-.045em]">Stay in motion.</h2><div className="mt-7 space-y-4">{activities.length ? activities.slice(0,4).map(activity => <div key={activity.id} className="border-b border-hairline pb-4"><p className="text-sm font-semibold">{activity.description}</p><p className="mt-1 font-[family-name:var(--font-ticker)] text-[.62rem] uppercase tracking-[.08em] text-stone">{activity.type.replace('_',' ')} · {activity.customer?.companyName ?? activity.opportunity?.title ?? 'Internal'}</p></div>) : <p className="py-5 text-sm text-stone">No upcoming activities are due.</p>}</div></aside></section>
    {isManager && <section className="mt-16 border-t border-hairline pt-8"><p className="eyebrow">Team signal</p><div className="mt-4 grid gap-5 md:grid-cols-3">{topTeam.map((rep,index) => <div key={rep.id} className="group border-b border-hairline py-5 transition-colors hover:bg-bronze-light md:border-t md:px-5"><p className="font-[family-name:var(--font-display)] text-4xl text-[#D6AA83]">0{index+1}</p><p className="mt-5 font-semibold">{rep.name}</p><p className="mt-1 text-sm text-stone">{rep.wonCount} won · {money(rep.openPipelineValue)} open</p></div>)}{!topTeam.length && <p className="text-sm text-stone">No team performance data available.</p>}</div></section>}
  </div>;
}
