import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../api/client';
import type { Opportunity, PipelineStage } from '../types';

const STAGES: PipelineStage[] = ['NEW', 'CONTACTED', 'QUALIFIED', 'PROPOSAL', 'NEGOTIATION', 'WON', 'LOST'];
const label = (stage: string) => stage.toLowerCase().replace(/\b\w/g, value => value.toUpperCase());
const money = (value: number) => new Intl.NumberFormat('en-US', { style:'currency', currency:'USD', notation:value >= 1000000 ? 'compact' : 'standard', maximumFractionDigits:value >= 1000000 ? 1 : 0, minimumFractionDigits:0 }).format(Number(value));
export default function PipelinePage() {
  const [opportunities, setOpportunities] = useState<Opportunity[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { api.get('/opportunities').then(res => setOpportunities(res.data.opportunities)).catch(() => setError('Pipeline data could not be loaded.')).finally(() => setLoading(false)); }, []);
  const grouped = useMemo(() => Object.fromEntries(STAGES.map(stage => [stage, opportunities.filter(opportunity => opportunity.stage === stage)])) as Record<PipelineStage, Opportunity[]>, [opportunities]);
  const openValue = opportunities.filter(item => !['WON','LOST'].includes(item.stage)).reduce((total,item) => total + Number(item.dealValue), 0);
  if (loading) return <div className="fade-in py-20 text-stone">Mapping your pipeline…</div>; if (error) return <div className="fade-in border-l-2 border-signal-negative py-5 pl-5 text-signal-negative">{error}</div>;
  return <div className="fade-in"><section className="flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><div><p className="eyebrow">Opportunity map</p><h1 className="page-title">The living<br/><i>pipeline.</i></h1></div><div className="border-l border-hairline pl-5"><p className="eyebrow">Live pipeline value</p><p className="mt-2 font-[family-name:var(--font-display)] text-4xl tracking-[-.05em] tabular-nums">{money(openValue)}</p></div></section><div className="section-rule"/>
    <section className="grid gap-x-7 gap-y-12 sm:grid-cols-2 xl:grid-cols-5">{STAGES.filter(stage => !['WON','LOST'].includes(stage)).map((stage,index) => { const items = grouped[stage]; const total = items.reduce((sum,item) => sum + Number(item.dealValue),0); return <article key={stage} className="min-w-0 border-t-2 border-charcoal pt-4"><p className="eyebrow">0{index + 1} / {items.length} deals</p><div className="mt-2 flex items-baseline justify-between gap-2"><h2 className="font-[family-name:var(--font-display)] text-3xl tracking-[-.05em]">{label(stage)}</h2><span className="font-[family-name:var(--font-ticker)] text-[.66rem] text-stone">{money(total)}</span></div><div className="mt-7 space-y-3">{items.length ? items.map(item => <Link key={item.id} to={`/leads/${item.leadId}`} className="group block border-b border-hairline pb-4"><p className="font-[family-name:var(--font-display)] text-xl leading-tight transition-colors group-hover:text-bronze">{item.title}</p><p className="mt-2 text-sm text-stone">{item.lead.companyName}</p><div className="mt-4 flex items-center justify-between font-[family-name:var(--font-ticker)] text-[.65rem] text-stone"><span>{item._count?.activities ?? 0} ACTIVITIES</span><span className="text-charcoal">{money(item.dealValue)}</span></div></Link>) : <p className="py-4 text-sm italic text-stone">No opportunities here.</p>}</div></article>; })}</section>
    <section className="mt-16 grid gap-10 border-t border-hairline pt-8 md:grid-cols-2">{(['WON','LOST'] as PipelineStage[]).map(stage => <div key={stage}><p className="eyebrow">{stage === 'WON' ? 'Closed / won' : 'Closed / lost'}</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-3">{grouped[stage].length ? grouped[stage].map(item => <Link key={item.id} to={`/leads/${item.leadId}`} className="text-sm font-semibold text-charcoal underline decoration-hairline underline-offset-4 transition-colors hover:text-bronze">{item.title} <span className="font-normal text-stone">{money(item.dealValue)}</span></Link>) : <p className="text-sm text-stone">No closed opportunities.</p>}</div></div>)}</section>
  </div>;
}
