import { useEffect, useState } from 'react';
import api from '../api/client';
import type { RepPerformance } from '../types';
const money = (value: number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:value >= 1000000 ? 'compact' : 'standard',maximumFractionDigits:1}).format(value);
export default function TeamPage() {
  const [team,setTeam] = useState<RepPerformance[]>([]); const [error,setError] = useState(''); const [loading,setLoading] = useState(true);
  useEffect(() => { api.get('/dashboard/team-performance').then(res => setTeam(res.data.teamPerformance)).catch(() => setError('Team performance could not be loaded.')).finally(() => setLoading(false)); }, []);
  if (loading) return <div className="fade-in py-20 text-stone">Reading team performance…</div>; if (error) return <div className="fade-in border-l-2 border-signal-negative py-5 pl-5 text-signal-negative">{error}</div>;
  const ranked = [...team].sort((a,b) => b.wonValue - a.wonValue); const teamOpen = ranked.reduce((total,rep) => total + rep.openPipelineValue,0);
  return <div className="fade-in"><section className="grid items-end gap-8 md:grid-cols-[1.25fr_.75fr]"><div><p className="eyebrow">Manager view / team performance</p><h1 className="page-title">Human signal,<br/><i>made visible.</i></h1><p className="page-intro">Live production metrics across every assigned territory. Rankings use closed-won value; open pipeline remains visible alongside it.</p></div><div className="border-l border-hairline pl-6"><p className="eyebrow">Collective open value</p><p className="mt-2 font-[family-name:var(--font-display)] text-4xl tracking-[-.05em]">{money(teamOpen)}</p></div></section><div className="section-rule"/>
    <section className="grid gap-6 border-y border-hairline py-7 md:grid-cols-3">{ranked.slice(0,3).map((rep,index) => <article key={rep.id} className="group border-b border-hairline py-5 last:border-0 md:border-b-0 md:border-r md:px-6 md:first:pl-0 md:last:border-0"><p className="font-[family-name:var(--font-display)] text-5xl text-[#D6AA83]">0{index+1}</p><h2 className="mt-10 font-[family-name:var(--font-display)] text-3xl tracking-[-.04em]">{rep.name}</h2><p className="mt-2 text-sm text-stone">{rep.leadsCount} prospects · {rep.customersCount} accounts</p><div className="mt-8 flex justify-between border-t border-hairline pt-4"><span className="eyebrow">Closed won</span><span className="font-[family-name:var(--font-display)] text-xl">{money(rep.wonValue)}</span></div></article>)}{!ranked.length && <p className="text-sm text-stone">No sales reps are available.</p>}</section>
    <section className="mt-16"><p className="eyebrow">Full roster</p><div className="mt-5 overflow-x-auto"><table className="editorial-table"><thead><tr><th className="pl-0">Representative</th><th>Prospects</th><th>Opportunities</th><th className="num-col">Open value</th><th className="num-col pr-0">Closed won</th></tr></thead><tbody>{ranked.map(rep => <tr key={rep.id}><td className="pl-0"><p className="font-semibold">{rep.name}</p><p className="mt-1 text-xs text-stone">{rep.email}</p></td><td>{rep.leadsCount}</td><td>{rep.opportunitiesCount}</td><td className="num-col">{money(rep.openPipelineValue)}</td><td className="num-col pr-0 font-[family-name:var(--font-display)] text-lg">{money(rep.wonValue)}</td></tr>)}</tbody></table></div></section>
  </div>;
}
